config/routes.rb
AccessControl::Application.routes.draw do

  resources :users, :key => :member_id do
    resources :cards do
      member do
        post 'disable'
      end
    end
    
    member do
      post 'disable'
    end
  end

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user
  attr_accessible :card_id, :enabled, :site_code
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :member_id, :name
  has_many :cards
  
  # Use member_id as key
  def to_param
    member_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @user = User.find_by_member_id(params[:user_id])
    @cards = @user.cards

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @user = User.find_by_member_id(params[:user_id])
    @card = @user.cards.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @user = User.find_by_member_id(params[:user_id])
    @card = @user.cards.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/1/edit
  def edit
    @user = User.find_by_member_id(params[:user_id])
    @card = @user.cards.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    @user = User.find_by_member_id(params[:user_id])
    @card = @user.cards.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to user_card_path(@user, @card), notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @user = User.find_by_member_id(params[:user_id])
    @card = @user.cards.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to user_card_path(@user, @card), notice: 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @user = User.find_by_member_id(params[:user_id])
    @card = @user.cards.find(params[:id])

    respond_to do |format|
      format.html { redirect_to user_cards_path }
      format.json { head :no_content }
    end
  end
  
  # POST /cards/1/disable
  def disable
    @user = @user = User.find_by_member_id(params[:user_id])
    @card = @user.cards.find(params[:id])
    @card.update_attributes(:enabled => false)
    
    respond_to do |format|
      format.html { redirect_to user_cards_path, notice: "Card (#{@card.site_code}:#{@card.card_id}) was successfully disabled." }
      format.json { render json: :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_member_id(params[:id])
    @cards = @user.cards.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find_by_member_id(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find_by_member_id(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find_by_member_id(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= form_for [@user, @card] do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :card_id %><br />
    <%= f.number_field :card_id %>
  </div>
  <div class="field">
    <%= f.label :site_code %><br />
    <%= f.number_field :site_code %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br />
    <%= f.check_box :enabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', user_card_path(@user, @card) %> |
<%= link_to 'Back', user_cards_path %>

app/views/cards/index.html.erb
<h1>Cards for <%= @user.name %> (<%= @user.member_id %>)</h1>
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>Site Code</th>
		<th>Card</th>
    <th>Enabled</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.card_id %></td>
    <td><%= card.site_code %></td>
    <td><%= card.enabled %></td>
		<td><%= link_to 'Disable', disable_user_card_path(@user, card), method: :post, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Edit', edit_user_card_path(@user, card) %></td>
    <td><%= link_to 'Destroy', user_card_path(@user, card), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Card', new_user_card_path %>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', user_cards_path(@user) %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Card:</b>
  <%= @card.card_id %>
</p>

<p>
  <b>Site code:</b>
  <%= @card.site_code %>
</p>

<p>
  <b>Enabled:</b>
  <%= @card.enabled %>
</p>

<p>
  <b>User:</b>
  <%= @card.user %>
</p>


<%= link_to 'Edit', edit_user_card_path(@user, @card) %> |
<%= link_to 'Back', user_cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AccessControl</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.number_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Member</th>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.member_id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Member:</b>
  <%= @user.member_id %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<table>
  <tr>
    <th>Site Code</th>
		<th>Card</th>
    <th>Enabled</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<h3>Key Cards</h3>

<% @cards.each do |card| %>
  <tr>
    <td><%= card.card_id %></td>
    <td><%= card.site_code %></td>
    <td><%= card.enabled %></td>
		<td><%= link_to 'Disable', disable_user_card_path(@user, card), method: :post, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Edit', edit_user_card_path(@user, card) %></td>
    <td><%= link_to 'Destroy', user_card_path(@user, card), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>